### ISSUE TITLE
PSP Homebrew should not be labeled as PS1 titles

### ISSUE THREAD

**Issue by Invictaz** [jimbob4000/RetroFlow-Launcher#7]
PSP Homebrew is inside the /pspemu/game folder.
Now Retroflow launcher sees it as ps1 games.

The expected behavior is that it is assigned under it's own category, or placed under all homebrew.
There is also no button to reassign the various homebrew titles, like there is for Vita homebrew

**Comment by jimbob4000** [comment]
Thanks for reporting. 
I'll look into re-enabling the category override for the PSP and PS1 categories, so they can be assigned to the PSP category.

**Comment by Invictaz** [comment]
Thanks. But homebrew for psp is different than vita homebrew.

**Comment by jimbob4000** [comment]
Homebrew games are also made for other retro systems too, doubling the number of categories it's not a route I want to down.

**Comment by jimbob4000** [comment]
I've released a new version with resolves the issue:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.0

**Comment by Invictaz** [comment]
@jimbob4000 issue is not fixed. PSP Homebrew can only be override to psp or ps1 category, not to homebrew category. Why is that? You said here https://github.com/jimbob4000/RetroFlow-Launcher/issues/7#issuecomment-955042367 that you will let people choose 3 categories

**Comment by jimbob4000** [comment]
Apologies, we have a different idea of how this should be handled. 

I've explained the reason and believe this is how the majority of users would like it to behave.

**Comment by Invictaz** [comment]
The problem also is that if you assign a new category, the list jumps back to the PSVita game section instead of back to the PS1 section where the falsely categorized homebrews are.

**Comment by jimbob4000** [comment]
I'm not sue about the jumping issue, I think it just reloads and goes to the first category. I'll have a look. 

What folder would you expect cover art to come from if it's moved to homebrew, and would the cover be square? Thanks. 

The cover would be blank by default, do you have a suggestion?

**Comment by jimbob4000** [comment]
This should be resolved with the latest [3.1 release](https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/v3.1).

PS Vita, PSP, PS1 and Homebrew can all be moved between each other.

The jumping back to PS Vita request could not be achieved at this time unfortunately.
